### ISSUE TITLE
Multi Vesting V2

### ISSUE THREAD

**Issue by Caceresenzo** [datacrunch-com/datacrunch-contracts#9]
## Summary

The main motivation for this new version is to have all the vesting start at the listing date on a CEX.
Therefore we added a global startDate variable that, once set, will start the cliff countdown for every vesting.

The `creator` feature, which was originally for auto-creation from the backend, will be removed too.

At the end of the cliff, starts the vesting period with a linear distribution of tokens.
So, at the end of the cliff, 0 tokens are vested and at the end of the vesting period 100% of the tokens are vested.
Vested tokens can be withdrawn whenever the beneficiary call the `release()` function.

No self destruct function will be added.
The revokability will only be used for team members and advisors.

## Features:

- [x] Vesting should start with a global variable.
- [x] The start date should be settable by the owner.
- [x] A user can have multiple vesting. (#11)
- [x] A user can transfer a vesting to another beneficiary address.
- [x] A vesting can be revokable.
- [x] CRUNCHs are starting from 0 only after the cliff.

**Comment by KireBinn** [comment]
You did a nice job. Well done
